In [1]:
import numpy as np

a = np.random.randn(5)


In [2]:
print(a)

[ 0.99024395 -1.82329368  0.55170572 -0.70985683  0.28566139]


In [7]:
print(a.shape)
print(type(a.shape))

(5, 1)
<class 'tuple'>


In [4]:
print(a.T)

[ 0.99024395 -1.82329368  0.55170572 -0.70985683  0.28566139]


In [5]:
print(np.dot(a, a.T))

5.194861281915423


In [8]:
# a sugestão do professor é não utilizar o caso acima

a = np.random.randn(5,1)
print(a)
print(type(a))

[[1.55779743]
 [1.17740442]
 [1.78163278]
 [0.0289056 ]
 [3.29349462]]
<class 'numpy.ndarray'>


In [9]:
# Desse modo ficamos com o vetor
print(a.T)

[[1.55779743 1.17740442 1.78163278 0.0289056  3.29349462]]


In [10]:
# dois colchetes
print(np.dot(a, a.T))

[[2.42673282e+00 1.83415757e+00 2.77542296e+00 4.50290619e-02
  5.13059745e+00]
 [1.83415757e+00 1.38628116e+00 2.09770230e+00 3.40335754e-02
  3.87777511e+00]
 [2.77542296e+00 2.09770230e+00 3.17421535e+00 5.14991559e-02
  5.86779797e+00]
 [4.50290619e-02 3.40335754e-02 5.14991559e-02 8.35533435e-04
  9.52004224e-02]
 [5.13059745e+00 3.87777511e+00 5.86779797e+00 9.52004224e-02
  1.08471068e+01]]


In [13]:
# a = np.random.randn(5)
# a.shape = (5,) é um array rank 1 e, 
# para não gerar erros nos exercícios, devemos evitar

# a = np.random.randn(5, 1) 
# torna um vetor coluna e
# a.shape = (5, 1)

# assert(a.shape == (5, 1)) é uma forma de verificar antes de executar